### ISSUE TITLE
Missing '_costate' attribute error

### ISSUE THREAD

**Issue by ibagur** [Yujun-Shi/BLIP#2]
Hi,

I am trying this very interesting and novel approach on some experiments with sparse-reward environments. In my particular case I am making  use of a` QMLPBase` policy. Training over a task goes fine, but I get an error at the post processing with `agent.ng_post_processing(rollouts, task_idx)` as follows:

`AttributeError: 'Linear_Q' object has no attribute '_costate'`

Apparently the error has its origin at the `estimate_fisher()` function, where supposedly a backward hook is registered for the `Linear_Q` layers on both actor and critic networks (as defined under `QMLPBase`). It seems that this backward hook does not get triggered for the critic network, therefore the attribute `_costate` never gets created. This subsequently raises an error at the `update_fisher_exact()` function, as this function expects the `_costate` attribute to exist for every `Linear_Q` layer when calculating `H = (f_state*m._costate).sum()`.

Any suggestions on how to overcome this issue?

Many thanks

**Comment by Yujun-Shi** [comment]
Thanks for pointing out this bug! Already fixed in recent commit.
